# Documentation: https://roots.io/trellis/docs/local-development-setup/
wordpress_sites:
  rodserling.space:
    site_hosts:
      - development.rodserling.space
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    site_install: true
    site_title: The Rod Serling Memorial foundation
    admin_user: carolserling
    # admin_password: (defined in group_vars/development/vault.yml)
    admin_email: web@rodserling.space
    initial_permalink_structure: /%postname%/ # applied only at time of WP install and when `site_install: true`
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: http://development.rodserling.space
      wp_siteurl: http://development.rodserling.space/wp
      wp_env: development
      db_name: rodserlingdev
      db_user: dbuser
      # db_password: (defined in group_vars/development/vault.yml)
